codecov:
  require_ci_to_pass: yes

coverage:
  range: 65..100
  round: down
  precision: 2
  status:
    patch:
      default:
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
