coverage:
  range: 65..100
  round: down
  precision: 2
  require_ci_to_pass: yes
  if_no_uploads: error
  if_not_found: error
  if_ci_failed: error
ignore:
  - "*.kt"       # ignore coverage kt script
  - "*.kts"     # ignore coverage kts script