name: Feature branch CI

on:
  push:
    pull_request:
      branches:
        - 'master'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: sh ./gradlew test
  lint:
    name: Perform statical code cheks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: sh ./gradlew lint
